### ISSUE TITLE
Plugin generating wrong CSS classes?

### ISSUE THREAD

**Issue by chtenb** [jirutka/asciidoctor-highlight.js#20]
The sample code on the README yields the following output

```html
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-js" data-lang="js"><span class="hljs-built_in">console</span>.log(<span class="hljs-string">&#x27;Hello, world!&#x27;</span>)</code></pre>
</div>
</div>
```

Notice the `<pre class="highlight"><code class="language-js" data-lang="js">` part.

The default stylesheets in the highlight.js repository all have the following rules:

```css
pre code.hljs {
  display: block;
  overflow-x: auto;
  padding: 1em;
}

code.hljs {
  padding: 3px 5px;
}

.hljs {
  color: #586e75;
  background: #fdf6e3;
}

.hljs ::selection {
  color: #93a1a1;
}
```

They don't match up. Is this on purpose, or does this plugin need updating?
